# Generated by Django 5.2.5 on 2025-08-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='early_leave_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('sick', 'ลาป่วย'), ('personal', 'ลากิจ'), ('vacation', 'ลาพักร้อน'), ('other', 'อื่นๆ')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('normal', 'ปกติ'), ('leave', 'ลา'), ('remote', 'ปฏิบัติงานนอกสถานที่'), ('absent', 'ขาดงาน')], default='normal', max_length=50),
        ),
    ]
