# Generated by Django 5.2.5 on 2025-08-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role_alter_customuser_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reset_token',
        ),
    ]
