# Generated by Django 5.2.5 on 2025-09-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(default='-', max_length=200, verbose_name='ชื่อห้องวิจัย (อังกฤษ)'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_th',
            field=models.CharField(default='-', max_length=200, verbose_name='ชื่อห้องวิจัย (ไทย)'),
        ),
    ]
