# Generated by Django 5.2.5 on 2025-09-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_department_name_department_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='quota_casual',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='quota_sick',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='quota_vacation',
        ),
    ]
