# Generated by Django 5.2.5 on 2025-09-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_quota_casual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='external_department',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='หน่วยงานภายนอก'),
        ),
    ]
