# Generated by Django 5.2.5 on 2025-09-13 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_external_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='หัวหน้าห้องวิจัย'),
        ),
        migrations.AlterField(
            model_name='department',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='approver_departments', to=settings.AUTH_USER_MODEL, verbose_name='ผู้มีสิทธิ์อนุมัติ'),
        ),
    ]
