# Generated by Django 5.2.5 on 2025-08-09 05:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOutsideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time_period', models.CharField(choices=[('full', 'ทั้งวัน'), ('morning', 'ครึ่งเช้า'), ('afternoon', 'ครึ่งบ่าย')], max_length=10)),
                ('reason', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติ'), ('rejected', 'ไม่อนุมัติ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=10)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_outside', to=settings.AUTH_USER_MODEL)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_work_outside', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
