# Generated by Django 5.2.5 on 2025-09-13 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_from_outside', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsiderequest',
            name='proxy_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_work_outside_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutsiderequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_outside_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
