# Generated by Django 5.2.5 on 2025-09-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('public', 'วันหยุดราชการ'), ('company', 'วันหยุดบริษัท'), ('religious', 'วันหยุดทางศาสนา'), ('other', 'อื่น ๆ')], default='public', max_length=20),
        ),
    ]
