# Generated by Django 5.2.5 on 2025-08-13 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-request_date']},
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='time_period',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='days',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_half',
            field=models.CharField(choices=[('full', 'ทั้งวัน'), ('morning', 'ครึ่งเช้า'), ('afternoon', 'ครึ่งบ่าย')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_half',
            field=models.CharField(choices=[('full', 'ทั้งวัน'), ('morning', 'ครึ่งเช้า'), ('afternoon', 'ครึ่งบ่าย')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='advance_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='allow_backdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='consumes_quota',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='default_quota',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_approve_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave.leavetype'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_for_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='LeaveQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('quota_total', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('quota_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'leave_type', 'year')},
            },
        ),
    ]
