# Generated by Django 5.2.5 on 2025-08-15 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leaverequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, help_text='ถ้าลาแทนคนอื่น ให้ระบุคนนี้', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests_on_behalf', to=settings.AUTH_USER_MODEL),
        ),
    ]
