# Generated by Django 5.2.5 on 2025-08-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaverequest_on_behalf_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='substitute_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
