# Generated by Django 5.2.5 on 2025-09-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leaverequest_substitute_acknowledged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='end_half',
            new_name='period',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='start_half',
        ),
    ]
